import { FormEvent, KeyboardEvent, useEffect, useRef, useState } from 'react';
import { BmapDiagnosisCard } from '../components/BmapDiagnosisCard';
import { GateWarning } from '../components/GateWarning';
import type { Message, Phase } from '../types';

interface Props { phases: Phase[]; activePhase: string; onCommandOpen: () => void; onAcceptRisk: () => void; onSecondSource: () => void; onExperiment: () => void; onBrief: () => void; onNewCycleNote?: string; }
const prompts = ['¿Qué comportamiento debe ocurrir, y por qué no ocurre hoy?', 'Trae la evidencia: ¿qué dato sostiene la causa Ability?', 'Si avanzas sin gate, ¿qué riesgo aceptas explícitamente?', '¿Cuál sería el cambio mínimo para mover el comportamiento?'];
const initialMessages: Message[] = [{ id: 1, role: 'user', content: 'Tengo un problema de activación: muchos sellers llegan al Aha, pero no configuran el segundo envío.' }, { id: 2, role: 'assistant', variant: 'diagnosis' }, { id: 3, role: 'assistant', variant: 'gate' }];
export function Workspace({ phases, activePhase, onCommandOpen, onAcceptRisk, onSecondSource, onExperiment, onBrief, onNewCycleNote }: Props) {
  const selected = phases.find((phase) => phase.key === activePhase) ?? phases[1];
  const [messages, setMessages] = useState<Message[]>(initialMessages);
  const [input, setInput] = useState('');
  const [promptIndex, setPromptIndex] = useState(0);
  const streamRef = useRef<HTMLElement>(null);
  useEffect(() => { const id = window.setInterval(() => setPromptIndex((value) => (value + 1) % prompts.length), 4200); return () => window.clearInterval(id); }, []);
  useEffect(() => { if (onNewCycleNote) addAiNote(onNewCycleNote); }, [onNewCycleNote]);
  useEffect(() => { streamRef.current?.scrollTo({ top: streamRef.current.scrollHeight }); }, [messages]);
  const addAiNote = (content: string) => setMessages((current) => [...current, { id: Date.now(), role: 'assistant', content }]);
  const send = () => { const text = input.trim(); if (!text) return; setMessages((current) => [...current, { id: Date.now(), role: 'user', content: text }]); setInput(''); if (text.startsWith('/brief')) { onBrief(); addAiNote('Brief exportado en Markdown. También queda vivo en el panel derecho.'); return; } if (text.startsWith('/experimento')) { onExperiment(); addAiNote('Detecto intención de pasar a F3. Puedo ayudarte, pero dejo visible el gate F1 si no cerramos la segunda fuente.'); return; } if (/entrevista|grabaci[oó]n|segunda fuente|2ª fuente/i.test(text)) { onSecondSource(); addAiNote('Gate F1 mucho más sólido. Ahora sí podemos diseñar una intervención mínima en F2 sin depender solo de una fuente cuantitativa.'); return; } addAiNote('Lo tomo como nueva evidencia conversacional. Para que entre al brief, dime si es comportamiento objetivo, evidencia, hipótesis o métrica de éxito.'); };
  const submit = (event: FormEvent) => { event.preventDefault(); send(); };
  const keyDown = (event: KeyboardEvent<HTMLTextAreaElement>) => { if ((event.metaKey || event.ctrlKey) && event.key === 'Enter') { event.preventDefault(); send(); } };
  const closeGate = () => addAiNote('Perfecto. Mantengo F1 abierto. Busca una 2ª fuente: entrevista breve, sesión grabada o evento de abandono en configuración de envío.');
  const advance = () => { onAcceptRisk(); addAiNote('Avanzamos a F2 con riesgo explícito. El brief mantiene el tag para que no parezca un diagnóstico cerrado.'); };
  return <section className="workspace-view"><header className="conversation-header"><div className="phase-chip"><span className="live-dot"/><strong>{selected.key} · {selected.label}</strong><span className="chip-divider"/><span>{selected.note || 'gate abierto'}</span></div><span className="cycle-name">Cliff de activación post-Aha</span><button className="command-button" type="button" onClick={onCommandOpen}>⌘K</button></header><section ref={streamRef} className="message-stream scrim" aria-live="polite"><div className="stream-inner">{messages.map((message) => { if (message.variant === 'diagnosis') return <article className="ai-message" key={message.id}><div className="ai-avatar">D</div><div className="ai-body"><p><strong>Voy a mantenernos en F1 · Diagnose.</strong> El comportamiento ya está definido, pero todavía falta una segunda fuente para afirmar que la causa es Ability y no Prompt.</p><BmapDiagnosisCard /></div></article>; if (message.variant === 'gate') return <GateWarning key={message.id} onCloseGate={closeGate} onAdvance={advance} />; if (message.role === 'user') return <div className="user-message" key={message.id}>{message.content}</div>; return <article className="ai-message" key={message.id}><div className="ai-avatar">D</div><div className="ai-body"><p>{message.content}</p></div></article>; })}</div></section><form className="chat-input-wrap" onSubmit={submit}><div className={`chat-input ${input.trim() ? 'has-text' : ''}`}><label className="sr-only" htmlFor="messageInput">Mensaje</label><textarea id="messageInput" rows={2} autoComplete="off" value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={keyDown}/><div className="placeholder-line" aria-hidden="true">{prompts[promptIndex]}<span className="caret"/></div><div className="input-meta-row"><div className="command-chips">{['/nuevo-ciclo','/brief','/experimento'].map((command) => <button type="button" key={command} onClick={() => setInput(command)}>{command}</button>)}</div><div className="send-area"><span>⌘↵ enviar</span><button className="send-button" type="submit" aria-label="Enviar">➜</button></div></div></div></form></section>;
}
